name: Download NarouR18 Novels

on:
  schedule:
    - cron: '0 15 * * *'  # 毎日 15:00 UTC（= 日本時間 0:00）に実行
  workflow_dispatch:       # 手動実行も許可

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install requests beautifulsoup4 g4f[all]

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Run Python Script
        env:
          RCLONE_CONFIG: ${{ github.workspace }}/rclone.conf
        run: |
          python narouR18/download_narouR18.py

      - name: Upload to Google Drive via rclone
        env:
          RCLONE_CONFIG: ${{ github.workspace }}/rclone.conf
        run: |
          rclone copy /tmp/narouR18_dl drive: --transfers=4 --checkers=8 --fast-list
